### ISSUE TITLE
blanco.io appears to have a good Site Cert, use https?

### ISSUE THREAD

**Issue by Grossdm** [ZacBlanco/zacblanco.github.io#10]
When I load https://blanco.io Firefox says that it "...has blocked parts of this page that are not secure", but the site certificate appears valid.

Perhaps you should update your links to [https](https://blanco.io).
Also, you might consider redirecting from http to https.

Kind regards,
Doug

**Comment by ZacBlanco** [comment]
I just saw this issue..thanks Doug!

I will take a look into moving all site resources to `https`

**Comment by Grossdm** [comment]
It looks like you can close this issue now - I no longer get any certificate warnings. 👍

**Comment by ZacBlanco** [comment]
Thanks!
